
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  PrismaClientKnownRequestError,
  PrismaClientUnknownRequestError,
  PrismaClientRustPanicError,
  PrismaClientInitializationError,
  PrismaClientValidationError,
  getPrismaClient,
  sqltag,
  empty,
  join,
  raw,
  skip,
  Decimal,
  Debug,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Extensions,
  warnOnce,
  defineDmmfProperty,
  Public,
  getRuntime,
  createParam,
} = require('./runtime/wasm-compiler-edge.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.1.0
 * Query Engine version: ab635e6b9d606fa5c8fb8b1a7f909c3c3c1c98ba
 */
Prisma.prismaVersion = {
  client: "7.1.0",
  engine: "ab635e6b9d606fa5c8fb8b1a7f909c3c3c1c98ba"
}

Prisma.PrismaClientKnownRequestError = PrismaClientKnownRequestError;
Prisma.PrismaClientUnknownRequestError = PrismaClientUnknownRequestError
Prisma.PrismaClientRustPanicError = PrismaClientRustPanicError
Prisma.PrismaClientInitializationError = PrismaClientInitializationError
Prisma.PrismaClientValidationError = PrismaClientValidationError
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = sqltag
Prisma.empty = empty
Prisma.join = join
Prisma.raw = raw
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = Extensions.getExtensionContext
Prisma.defineExtension = Extensions.defineExtension

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes





/**
 * Enums
 */
exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserInfoScalarFieldEnum = {
  userNo: 'userNo',
  emlAddr: 'emlAddr',
  userNm: 'userNm',
  userRole: 'userRole',
  proflImg: 'proflImg',
  userBiogp: 'userBiogp',
  encptPswd: 'encptPswd',
  reshToken: 'reshToken',
  useYn: 'useYn',
  delYn: 'delYn',
  lastLgnDt: 'lastLgnDt',
  lastPswdChgDt: 'lastPswdChgDt',
  crtNo: 'crtNo',
  crtDt: 'crtDt',
  updtNo: 'updtNo',
  updtDt: 'updtDt',
  delNo: 'delNo',
  delDt: 'delDt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.UserRole = exports.$Enums.UserRole = {
  ADMIN: 'ADMIN',
  USER: 'USER'
};

exports.YnStatus = exports.$Enums.YnStatus = {
  Y: 'Y',
  N: 'N'
};

exports.Prisma.ModelName = {
  UserInfo: 'UserInfo'
};
/**
 * Create the Client
 */
const config = {
  "previewFeatures": [],
  "clientVersion": "7.1.0",
  "engineVersion": "ab635e6b9d606fa5c8fb8b1a7f909c3c3c1c98ba",
  "activeProvider": "postgresql",
  "inlineSchema": "// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ngenerator client {\n  provider = \"prisma-client-js\"\n  output   = \"./client/prisma\"\n}\n\ndatasource db {\n  provider = \"postgresql\"\n}\n\n// 사용자 권한 enum\nenum UserRole {\n  ADMIN\n  USER\n}\n\n// Y/N 상태 enum\nenum YnStatus {\n  Y\n  N\n}\n\n// 사용자 기본 정보 테이블\nmodel UserInfo {\n  userNo        Int      @id @default(autoincrement()) @map(\"user_no\")\n  emlAddr       String   @unique @map(\"eml_addr\")\n  userNm        String   @unique @map(\"user_nm\")\n  userRole      UserRole @default(USER) @map(\"user_role\")\n  proflImg      String?  @map(\"profl_img\")\n  userBiogp     String?  @map(\"user_biogp\")\n  encptPswd     String   @map(\"encpt_pswd\")\n  reshToken     String?  @map(\"resh_token\")\n  useYn         YnStatus @default(Y) @map(\"use_yn\")\n  delYn         YnStatus @default(N) @map(\"del_yn\")\n  lastLgnDt     String?  @default(dbgenerated(\"to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD\\\"T\\\"HH24:MI:SS\\\"Z\\\"')\")) @map(\"last_lgn_dt\")\n  lastPswdChgDt String?  @default(dbgenerated(\"to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD\\\"T\\\"HH24:MI:SS\\\"Z\\\"')\")) @map(\"last_pswd_chg_dt\")\n  crtNo         Int?     @map(\"crt_no\")\n  crtDt         String   @default(dbgenerated(\"to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD\\\"T\\\"HH24:MI:SS\\\"Z\\\"')\")) @map(\"crt_dt\")\n  updtNo        Int?     @map(\"updt_no\")\n  updtDt        String   @default(dbgenerated(\"to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD\\\"T\\\"HH24:MI:SS\\\"Z\\\"')\")) @map(\"updt_dt\")\n  delNo         Int?     @map(\"del_no\")\n  delDt         String?  @map(\"del_dt\")\n\n  @@map(\"user_info\")\n}\n"
}

config.runtimeDataModel = JSON.parse("{\"models\":{\"UserInfo\":{\"fields\":[{\"name\":\"userNo\",\"kind\":\"scalar\",\"type\":\"Int\",\"dbName\":\"user_no\"},{\"name\":\"emlAddr\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"eml_addr\"},{\"name\":\"userNm\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"user_nm\"},{\"name\":\"userRole\",\"kind\":\"enum\",\"type\":\"UserRole\",\"dbName\":\"user_role\"},{\"name\":\"proflImg\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"profl_img\"},{\"name\":\"userBiogp\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"user_biogp\"},{\"name\":\"encptPswd\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"encpt_pswd\"},{\"name\":\"reshToken\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"resh_token\"},{\"name\":\"useYn\",\"kind\":\"enum\",\"type\":\"YnStatus\",\"dbName\":\"use_yn\"},{\"name\":\"delYn\",\"kind\":\"enum\",\"type\":\"YnStatus\",\"dbName\":\"del_yn\"},{\"name\":\"lastLgnDt\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"last_lgn_dt\"},{\"name\":\"lastPswdChgDt\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"last_pswd_chg_dt\"},{\"name\":\"crtNo\",\"kind\":\"scalar\",\"type\":\"Int\",\"dbName\":\"crt_no\"},{\"name\":\"crtDt\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"crt_dt\"},{\"name\":\"updtNo\",\"kind\":\"scalar\",\"type\":\"Int\",\"dbName\":\"updt_no\"},{\"name\":\"updtDt\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"updt_dt\"},{\"name\":\"delNo\",\"kind\":\"scalar\",\"type\":\"Int\",\"dbName\":\"del_no\"},{\"name\":\"delDt\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"del_dt\"}],\"dbName\":\"user_info\"}},\"enums\":{},\"types\":{}}")
defineDmmfProperty(exports.Prisma, config.runtimeDataModel)
config.compilerWasm = {
  getRuntime: async () => require('./query_compiler_bg.js'),
  getQueryCompilerWasmModule: async () => {
    const loader = (await import('#wasm-compiler-loader')).default
    const compiler = (await loader).default
    return compiler
  }
}
if (typeof globalThis !== 'undefined' && globalThis['DEBUG'] || (typeof process !== 'undefined' && process.env && process.env.DEBUG) || undefined) {
  Debug.enable(typeof globalThis !== 'undefined' && globalThis['DEBUG'] || (typeof process !== 'undefined' && process.env && process.env.DEBUG) || undefined)
}

const PrismaClient = getPrismaClient(config)
exports.PrismaClient = PrismaClient
Object.assign(exports, Prisma)
